# Generated by Django 3.2.4 on 2021-07-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210624_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
