# Generated by Django 3.2.4 on 2021-07-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_order_name_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_addresss1',
            new_name='street_address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_addresss2',
            new_name='street_address2',
        ),
    ]
